Monster antag headshots, updated flavor text, and eye fix
Tree445/Hearthstone pull request #388
Opened 2024-08-22 01:58 UTC by Juubo

adding in additional headshot options

## About The Pull Request
Adds undisguised vampire and werewolf headshot options and your human headshot (default). Adds in fang and pale skin descriptions for vampires. Removes the dead eye color change

## Why It's Good For The Game
adds a bit more immersion for the headshots if players have an alternative. Also gives better ways to recognize vampires other than they are "indistinguishable" from a lore perspective. Also removes the eye change with dead eyes and adding pink or red

2024-09-17 19:27 UTC, DavidAreYouSure commented
The dead white eyes are supposed to be a give away for vamps because otherwise unless you just cast holy magic on everyone you see you can't detect them and doing that is generally not effective long term. If you do allow color change make sure that nonundead can't get the same eye color by any means other than becoming undead themselves/taking undead eyes from something else

2024-09-19 09:34 UTC, Luctus-Comptus requested changes
if you are still working on this long as its up-to-date for the most part and good to go I approve since we are doing changes to monsters.... anyway at this point. least the framework will be there.

2024-09-24 13:52 UTC, Juubo commented
> The dead white eyes are supposed to be a give away for vamps because otherwise unless you just cast holy magic on everyone you see you can't detect them and doing that is generally not effective long term. If you do allow color change make sure that nonundead can't get the same eye color by any means other than becoming undead themselves/taking undead eyes from something else

I dont think it's intentional at all. The vampire lord and spawn have code to make the eyes red but they keep defaulting to white. I believe the issue is the undead night vision they are given is the cause, they go back to default color and don't seem to update no mater the updates on the bodyparts

2024-09-24 13:54 UTC, Juubo commented
> if you are still working on this long as its up-to-date for the most part and good to go I approve since we are doing changes to monsters.... anyway at this point. least the framework will be there.

It's a learning process to say the least. I'm having two issues with getting the eyes changing and getting examine text to show up for werewolves. I may tell this back and just leave stubs if someone else wants to trouble shoot these

2025-03-05 16:47 UTC, closed without merging