[DRAFT] Folds Bog and Watchmen together
Tree445/Hearthstone pull request #597
Opened 2024-10-06 11:48 UTC by AllCorruptingWyrm

## About The Pull Request

This is going to be controversial for a lot of reasons but the main issue is that Watchmen and Bog are redundant. To make a comparison, its like Dept Sec on Skyrat servers -- they effectively become their own antagonist in the worse of cases and in the best of cases they don't exist. Departmental Security also encourages factionalism with departments when they are supposed to be working towards one goal, defeating the antagonist. Before accusations are made, I used to be a Sheriff main.

Anyway, this PR ensures the new city watch can't be inhumane worshippers and fulfill the role as security for the town of Rockhill. Regular watchmen get a listening stone, the Sheriff gets a ring. Also to reflect their status, their mister account is no longer dirt poor (lol?)

## Why It's Good For The Game

Mentioned above. Discuss.

2024-10-06 12:42 UTC, Evie7056 requested changes
Please look onto the compile error. This also has few styling errors that may or may not cause compile fail.

2024-10-06 12:42 UTC, Evie7056 commented on code/modules/jobs/job_types/roguetown/garrison/townguard.dm
> +		allowed_patrons = ALL_DIVINE_PATRONS
extra tab

2024-10-06 12:42 UTC, Evie7056 commented on code/modules/jobs/job_types/roguetown/garrison/sheriff.dm
> +		allowed_patrons = ALL_DIVINE_PATRONS
extra tab

2024-10-06 12:42 UTC, Evie7056 commented on code/modules/jobs/job_types/roguetown/garrison/townguard.dm
> +	tutorial = tutorial = "You are a member of the now consolidated city watch after the merger with the Bogmen. As such, you have been granted more training and gone through basic purity exercises as w
`tutorial = tutorial`
wont compile for sure. remove a var inside a var

2024-10-06 12:42 UTC, Evie7056 commented on code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
> +		allowed_patrons = ALL_DIVINE_PATRONS
extra tab

2024-10-06 12:42 UTC, Evie7056 commented on code/modules/jobs/job_types/roguetown/garrison/bogmaster.dm
> +		allowed_patrons = ALL_DIVINE_PATRONS
may not necessary cause compile error, but it it's still not good to do this

2024-10-06 12:44 UTC, Evie7056 commented on code/modules/jobs/job_types/roguetown/garrison/townguard.dm
> -	display_order = JDO_TOWNGUARD
I think you also ate here an extra line

2024-10-06 14:44 UTC, oprimeolt commented
I'd say keep bogmaster as just 'mans the bog gate'

2024-10-06 16:46 UTC, Feralape commented
Won't switching total positions to 0 make it an infinite slot?

2024-10-10 18:19 UTC, Decoy1240 commented
> Won't switching total positions to 0 make it an infinite slot?

No -1 I think is how you do that look at begger?

2024-10-10 18:19 UTC, Decoy1240 commented
> I'd say keep bogmaster as just 'mans the bog gate' 

This probably would be merged with a update to also remove the bog gate and add a new one

2024-10-19 23:19 UTC, AllCorruptingWyrm commented
due to a vote difference of 3, a compromise will be met.

2024-10-19 23:19 UTC, closed without merging